version: "3.5"

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - PORT=8080
      - DATABASE_URL=mongodb://admin:123@db:27017
    depends_on:
      - db
    networks:
      - rinha-backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "70MB"

  api02:
    <<: *api
    hostname: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./.config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - rinha-backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  db:
    image: docker.io/bitnami/mongodb:latest
    environment:
      - MONGODB_DATABASE=rinha
      - MONGODB_ADVERTISED_HOSTNAME=db
      - MONGODB_ROOT_USER=admin
      - MONGODB_ROOT_PASSWORD=123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - "27017:27017"
    volumes:
      - ./.config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - rinha-backend
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: "380MB"

networks:
  rinha-backend:
    driver: bridge
