version: "3.5"

services:
  # api01: &api
  #   build: .
  #   hostname: api01
  #   environment:
  #     - PORT=8080
  #     - DATABASE_URL=mongodb://admin:123@db:27017
  #   depends_on:
  #     - db
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.3"
  #         memory: "85MB"

  # api02:
  #   <<: *api
  #   hostname: api02

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./.config/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api01
  #     - api02
  #   ports:
  #     - "9999:9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.2"
  #         memory: "30MB"

  db:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
      - MONGO_INITDB_DATABASE=rinha
    ports:
      - "27017:27017"
    volumes:
      - ./.config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "350MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
